### ISSUE TITLE
Add ability to pass environment variables

### ISSUE THREAD

**Issue by kluevandrew** [tarantool/tarantool-lua-debugger-vscode#10]
Motivation: 

- Tarantool configuration can be passed thorugh system environment variables (https://www.tarantool.io/en/doc/latest/reference/configuration/#setting-via-environment-variables)
- Some applications (e.g. cartridge/tdg2) also works with environment variables

Seems it will be useful if we add ability to pass environment variables to process launched under debugger like that:

```json
{
    ...
    "configurations": [
        {
            ...
            "env": {
               "SOME_ENVIRONMENT_VARIABLE_NAME": "SOME_ENVIRONMENT_VARIABLE_VALUE"
            }
        }
    ]
}
```

**Comment by usenko-timur** [comment]
The functionality you described is already implemented. You can set the value of environment variables as you described.
